// Objective-C API for talking to muggle Go package.
//   gobind -lang=objc muggle
//
// File is generated by gobind. Do not edit.

#ifndef __Muggle_H__
#define __Muggle_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL MuggleStartInstance(NSData* pbConfigBytes, NSError** error);

#endif
