
// Objective-C API for talking to the following Go packages
//
//	muggle
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Muggle_FRAMEWORK_H__
#define __Muggle_FRAMEWORK_H__

#include "Muggle.objc.h"
#include "Universe.objc.h"

#endif
